# Generated by Django 4.1.1 on 2022-09-29 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datentime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 0, 8, 27, 865233)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='faculty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
