# Generated by Django 4.1.1 on 2022-09-30 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_delete_adminuser_alter_attendance_datentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datentime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 54, 34, 916580)),
        ),
    ]
