# Generated by Django 4.0.2 on 2022-10-01 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_imagestore_alter_attendance_datentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datentime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 17, 57, 18, 330483)),
        ),
    ]
